################################################################################
### WINDOWS, WORKSPACES, AND LAYERS ###
################################################################################

# ----------------------------------------------------- 
# Global Window Rules & Fixes
# ----------------------------------------------------- 

windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# ----------------------------------------------------- 
# Application-Specific Rules
# ----------------------------------------------------- 

# Hyprland-run
windowrule {
    name = move-hyprland-run
    match:class = hyprland-run
    move = 20 monitor_h-120
    float = yes
}

# File Dialogs & Properties (Nautilus/Firefox)
windowrule {
    name = nautilus
    match:title = ^(Properties|Open|Save|firefox)
    float = true
    size = 600 600
    center = true
}

windowrule {
    name = nemo
    match:class = nemo
    match:title = ^(Open with)
    float = true
    size = 600 600
    center = true
}

# Image Viewer
windowrule {
    name = imv
    match:class = imv
    float = true
    size = 900 600
    center = true
}

layerrule {
    name = wofi_glass
    match:namespace = wofi
    blur = true
    ignore_alpha = 0.5
}


